<?php
// Autogenerated by "make sri" (and srihash_files.txt).
$GLOBALS["SRIHASHES"] = array(
"css/font-awesome.min.css" => "sha384-X7L1bhgb36bF1iFvaqvhgpaGpayKM+vXNNYRlF89BFA5s3vi1qZ8EX9086RlZjy1",
"css/style.css" => "sha384-E1C+SYCJWVnniihcGtf0JJasHW2qdiiWqjCAYJ4JWB4S/1dxhc0Te6V/xq/VCaK7",
"js/jquery-min.js" => "sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq",
"js/phonebook.js" => "sha384-buaxmCXlt4CJTHUtElVzSaH0jgxG5AVwFW7Yu/hjeeRk7OMoNThSxrZUvRLz3ELX",
);
?>
